const Icons = {
  eye_hide: require('../assets/icons/eye_hide.png'),
  eye: require('../assets/icons/eye.png'),
  cross: require('../assets/icons/cross.png'),
  home: require('../assets/icons/home.png'),
  colourcatalog: require('../assets/icons/colourcatalog.png'),
  gallery: require('../assets/icons/gallery.png'),
  primerproduct: require('../assets/icons/primerproduct.png'),
  productfinder: require('../assets/icons/productfinder.png'),
  sidemenu: require('../assets/icons/sidemenu.png'),
  paintcalculator: require('../assets/icons/paintcalculator.png'),
  camera: require('../assets/icons/camera.png'),
  meter: require('../assets/icons/meter.png'),
  maskgroup: require('../assets/icons/maskgroup.png'),
  maskgroup1: require('../assets/icons/maskgroup1.png'),
  crossb: require('../assets/icons/crossb.png'),
  profile: require('../assets/icons/profile.png'),
  mail: require('../assets/icons/mail.png'),
  rectangle: require('../assets/icons/rectangle.png'),
  x: require('../assets/icons/cross.png'),
  cross_green: require('../assets/icons/cross.png'),
  arrow_down: require('../assets/icons/cross.png'),
  bell: require('../assets/icons/mail.png'),
  blank_user: require('../assets/icons/profile.png'),
  // background: require('../assets/icons/background.png'),
  // green_plus: require('../assets/icons/green_plus.png'),
  // user1: require('../assets/icons/user1.png'),
  // green_tick_circle: require('../assets/icons/green_tick_circle.png'),
  // filter: require('../assets/icons/filter.png'),
  // grey_arrow: require('../assets/icons/grey_arrow.png'),
  // india: require('../assets/icons/india.png'),
  // england: require('../assets/icons/england.png'),
  // rectangle1: require('../assets/icons/rectangle1.png'),
  // black_plus: require('../assets/icons/black_plus.png'),
  // settings: require('../assets/icons/settings.png'),
  // gallery: require('../assets/icons/gallery.png'),
  // sort: require('../assets/icons/sort.png'),
  // ukrain: require('../assets/icons/ukrain.png'),
  // leasure: require('../assets/icons/leasure.png'),
  // next: require('../assets/icons/next.png'),
  // calender: require('../assets/icons/calender.png'),
  // rectangle2: require('../assets/icons/rectangle2.png'),
  // white_tick: require('../assets/icons/white_tick.png'),
  // rectangle3: require('../assets/icons/rectangle3.png'),
  // threedot: require('../assets/icons/threedot.png'),
  // plus: require('../assets/icons/plus.png'),
  // minus: require('../assets/icons/minus.png'),
  // documents: require('../assets/icons/documents.png'),
  // black_arrow: require('../assets/icons/black_arrow.png'),
  // edit: require('../assets/icons/edit.png'),
  // change: require('../assets/icons/change.png'),
  // plus_user: require('../assets/icons/plus_user.png'),
  // privacy: require('../assets/icons/privacy.png'),
  // logout: require('../assets/icons/logout.png'),
  // user_icon: require('../assets/icons/user_icon.png'),
  // notification: require('../assets/icons/notification.png'),
  // message: require('../assets/icons/message.png'),
  // count: require('../assets/icons/count.png'),
  // sms: require('../assets/icons/sms.png'),
  // gradient: require('../assets/icons/gradient.png'),
  // transparent_cross: require('../assets/icons/transparent_cross.png'),
  // transparent_tick: require('../assets/icons/transparent_tick.png'),
  // rectangle4: require('../assets/icons/rectangle4.png'),
  // tick_green: require('../assets/icons/tick_green.png'),
  // messages: require('../assets/icons/messages.png'),
  // setting: require('../assets/icons/setting.png'),
  // rectangle5: require('../assets/icons/rectangle5.png'),
  // group: require('../assets/icons/group.png'),
  // emoji: require('../assets/icons/emoji.png'),
  // threedot1: require('../assets/icons/threedot1.png'),
  // send: require('../assets/icons/send.png'),
  // attached: require('../assets/icons/attached.png'),
  // white_cross: require('../assets/icons/white_cross.png'),
  // log: require('../assets/icons/log.png'),
  // delete: require('../assets/icons/delete.png'),
  // noti: require('../assets/icons/noti.png'),
  // doc: require('../assets/icons/doc.png'),
  // menu1: require('../assets/icons/menu1.png'),
  // floating: require('../assets/icons/floating.png'),
  // filter_goals: require('../assets/icons/filter_goals.png'),
  // upload: require('../assets/icons/upload.png'),
  // sms_black: require('../assets/icons/sms_black.png'),
  // notification_green:require('../assets/icons/notification_green.png'),
  // messageshm:require('../assets/icons/messageshome.png'),
  // blank_gallery:require('../assets/icons/blank_gallery.png'),
};

export default Icons;
